repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: jetstack
  url: https://charts.jetstack.io
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: metrics-server
  url: https://kubernetes-sigs.github.io/metrics-server
- name: longhorn
  url: https://charts.longhorn.io

releases:
- name: metrics-server
  namespace: kube-system
  chart: metrics-server/metrics-server
  values:
  - /tmp/metrics-server-values.yaml
- name: ingress-nginx
  namespace: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  values:
  - /tmp/ingress-nginx-values.yaml  
- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  set:
  - name: crds.enabled
    value: "true"
- name: prometheus
  namespace: prometheus
  chart: prometheus-community/prometheus
  set:
  - name: alertmanager.enabled
    value: false
  - name: prometheus-pushgateway.enabled
    value: false
  - name: server.retention
    value: 2d
- name: longhorn
  namespace: longhorn-system
  chart: longhorn/longhorn
  set:
  - name: longhornUI.replicas
    value: 1
  - name: csi.attacherReplicaCount
    value: 1
  - name: csi.provisionerReplicaCount
    value: 1
  - name: csi.resizerReplicaCount
    value: 1
  - name: snapshotterReplicaCount
    value: 1
  - name: defaultSettings.defaultReplicaCount
    value: 1
  - name: persistence.defaultClassReplicaCount
    value: 1





