---
- name: common
  hosts: all
  any_errors_fatal: true
  tags:
    - common
  roles:
    - common

- name: Create etcd cluster
  hosts: etcd
  any_errors_fatal: true
  become: true
  tags:
    - etcd
  roles:
    - etcd

- name: Control plane components
  hosts: control_plane
  become: true
  any_errors_fatal: true
  tags:
    - control-plane
  roles:
    - control-plane

- name: Worker node components
  hosts: control_plane,worker
  become: true
  any_errors_fatal: true
  tags:
    - worker
  roles:
    - worker

- name: post-install
  hosts: etcd[0]
  any_errors_fatal: true
  become: true
  tags:
  - post-install
  tasks:
  - shell: "etcdctl --cert=/etc/kubernetes/pki/etcd/server.crt --key=/etc/kubernetes/pki/etcd/server.key --cacert=/etc/kubernetes/pki/etcd/ca.crt --insecure-skip-tls-verify put /coreos.com/network/config '{ \"Network\": \"10.244.0.0/16\", \"Backend\": {\"Type\": \"vxlan\"}}'"

- name: post-install
  hosts: all
  any_errors_fatal: true
  become: true
  tags:
    - post-install
  roles:
    - flannel

- name: chart-install
  hosts: control_plane[0]
  any_errors_fatal: true
  tags:
    - charts
  roles:
    - charts
