---
- name: Wait for availability of nodes
  hosts: all
  gather_facts: no
  tasks:
  - name: Wait for SSH to be available
    wait_for:
      port: 22
      host: "{{ ansible_host }}"
      delay: 1
      timeout: 600
      state: started
    delegate_to: localhost

- name: common
  hosts: all
  any_errors_fatal: true
  become: true
  tags:
    - common
  roles:
    - common

- name: Create etcd cluster
  hosts: etcd
  any_errors_fatal: true
  become: true
  tags:
    - etcd
  roles:
    - etcd

- name: Control plane components
  hosts: control_plane
  become: true
  any_errors_fatal: true
  tags:
    - control-plane
  roles:
    - control-plane

- name: Worker node components
  hosts: control_plane,worker
  become: true
  any_errors_fatal: true
  tags:
    - worker
  roles:
    - worker

- name: fetch-kubeconfig-label-nodes
  hosts: control_plane[0]
  any_errors_fatal: true
  become: true
  tags:
    - post-install
  tasks:
    - name: Fetch kubeconfig
      ansible.builtin.fetch:
        src: /root/.kube/config
        dest: /tmp/
        flat: yes
    - shell: "/usr/local/bin/kubectl label node {{ansible_hostname}} node-role.kubernetes.io/control-plane=true"
    - shell: "/usr/local/bin/kubectl taint nodes {{ansible_hostname}} node-role.kubernetes.io/control-plane:NoSchedule"

- name: install-cni-flannel
  hosts: all
  any_errors_fatal: true
  become: true
  tags:
    - post-install
  roles:
    - role: flannel
      when: cni == "flannel"

- name: install-cni-cilium
  hosts: control_plane[0]
  any_errors_fatal: true
  become: true
  tags:
    - post-install
  roles:
    - role: cilium
      when: cni == "cilium"

- name: install-cni-canal
  hosts: all
  any_errors_fatal: true
  become: true
  tags:
    - post-install
  roles:
    - role: canal
      when: cni == "canal"

- name: install-gvisor
  hosts: all
  any_errors_fatal: true
  become: true
  tags:
    - security
  roles:
    - role: gvisor
      when: security_hardening | default(false)

- name: chart-install
  hosts: control_plane[0]
  any_errors_fatal: true
  become: true
  tags:
    - charts
  roles:
    - charts

