---
- name: common
  hosts: all
  roles:
    - common

- name: Create etcd cluster
  hosts: etcd
  become: true
  any_errors_fatal: true
  roles:
    - etcd

- name: Control plane components
  hosts: control_plane
  become: true
  any_errors_fatal: true
  tags:
    - control-plane
  roles:
    - control-plane

- name: Worker node components
  hosts: worker
  become: true
  any_errors_fatal: true
  tags:
    - worker
  roles:
    - worker

- name: post-install
  hosts: control_plane[0]
  become: true
  tags:
    - post-install
  tasks:
    - name: CNI
      shell: "kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v{{canal_version|default('3.29.1')}}/manifests/canal.yaml"

