---

- name: Add NO_PROXY
  hosts: all
  become: true
  tasks:
  - set_fact:
      ip_address: "{% if internal_ip is defined and internal_ip != '' %}{{internal_ip}}{% else %}{{ansible_default_ipv4.address}}{% endif %}"
  - set_fact:
      all_ips: "{% for host in groups['all'] %}{{hostvars[host]['ip_address']}}{% if not loop.last %},{% endif %}{% endfor %}"
  - ansible.builtin.lineinfile:
      path: /etc/environment
      regexp: '^NO_PROXY='
      line: "NO_PROXY=127.0.0.1,localhost,10.151.0.0/16,10.152.0.0/16,10.96.0.10,10.96.0.1,.hetzner-test.site,*.hetzner-test.site,nip.io,*.nip.io,10.244.0.0/16,10.96.0.0/12,*.svc,*.cluster.local,{{all_ips}}"
  - ansible.builtin.lineinfile:
      path: /etc/environment
      regexp: '^no_proxy='
      line: "NO_PROXY=127.0.0.1,localhost,10.151.0.0/16,10.152.0.0/16,10.96.0.10,10.96.0.1,.hetzner-test.site,*.hetzner-test.site,nip.io,*.nip.io,10.244.0.0/16,10.96.0.0/12,*.svc,*.cluster.local,{{all_ips}}"
