- set_fact:
    arch: "{{ architecture[ansible_architecture|lower] }}"

- name: Delete temporary files
  ansible.builtin.file:
    path: "{{item}}"
    state: absent
  loop:
  - "/tmp/kubernetes-server-{{ansible_system | lower}}-{{ arch }}.tar.gz"
  - /tmp/kubernetes
  - /tmp/apiserver.cnf
  - /tmp/apiserver-etcd-client.csr
  - /tmp/apiserver-kubelet-client.csr
  - /tmp/apiserver.csr
  - /tmp/controller-manager.csr
  - /tmp/scheduler.csr
  - /tmp/sa.csr
  - /tmp/front-proxy-client.csr
  - /tmp/admin.csr
  - /tmp/controller-manager.crt
  - /tmp/scheduler.crt
  - /tmp/admin.key
  - /tmp/controller-manager.key
  - /tmp/scheduler.key
  - /tmp/sa.crt
  - /tmp/admin.crt
  - /tmp/etcd-ca.crt
  - /tmp/etcd-ca.key
  - /tmp/rbac.yaml
  ignore_errors: true
