- name: Download CNI binaries release
  ansible.builtin.get_url:
    url: "https://github.com/containernetworking/plugins/releases/download/v{{cni_version}}/cni-plugins-{{ansible_system | lower}}-{{ arch }}-v{{cni_version}}.tgz"
    dest: "/tmp/cni-plugins-{{ansible_system | lower}}-{{ arch }}-v{{cni_version}}.tgz"
    force: false
    mode: '0755'

- name: Untar CNI binaries release
  ansible.builtin.unarchive:
    src: "/tmp/cni-plugins-{{ansible_system | lower}}-{{ arch }}-v{{cni_version}}.tgz"
    dest: "/opt/cni/bin"
    remote_src: true
