- name: Install containerd
  package:
    name: containerd
    state: present
  register: install_containerd
- name: Configure containerd (1/3)
  shell: "mkdir -p /etc/containerd && containerd config default | tee /etc/containerd/config.toml"
  args:
    creates: /etc/containerd/config.toml
- name: Configure containerd (2/3)
  shell: "sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml"
- name: Configure containerd (3/3)
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: 'disabled_plugins'
    state: absent
- name: remove apparmor profile for runc (if present)
  shell: mkdir -p /etc/apparmor.d/disable && ln -s /etc/apparmor.d/runc /etc/apparmor.d/disable/ && apparmor_parser -R /etc/apparmor.d/runc
  failed_when: false
  when: ansible_os_family == 'Debian'
- name: Restart containerd
  systemd:
    name: containerd
    state: restarted
    daemon_reload: true
    enabled: true
  when: install_containerd.changed
