- name: Create folders
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true
  loop:
    - /etc/kubernetes/pki/etcd
    - /opt/cni/bin
    - /etc/cni/net.d

- include_tasks: certificate_authority.yml

- name: Install Base packages
  package:
    name: "{{item}}"
  loop:
    - unzip
    - conntrack
    - curl
    - tar
    - git
  ignore_errors: true

- include_tasks: cni.yml

- include_tasks: cleanup.yml
