- name: Create folders
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  loop:
    - /etc/kubernetes/pki
    - /opt/cni/bin
    - /etc/cni/net.d

- include_tasks: certificate_authority.yml

- name: Update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install Base packages
  package:
    name: ['unzip','conntrack','curl','tar','git','iptables']

- block:
  - name: Install pre-requisite packages
    yum:
      name: ['ca-certificates','iscsi-initiator-utils','gpg','jq','nfs-utils']
      update_cache: yes
  - name: Enable iscsid
    systemd:
      name: iscsid
      state: started
      enabled: yes
  when: ansible_os_family == 'RedHat'

- name: Install kernel pre-requisites
  ansible.builtin.shell: "dnf install -y kernel-modules-extra"
  async: 300
  poll: 0
  when: ansible_os_family == 'RedHat'

- set_fact:
    ip_address: "{% if internal_ip is defined and internal_ip != '' %}{{internal_ip}}{% else %}{{ansible_default_ipv4.address}}{% endif %}"
- set_fact:
    all_ips: "{% for host in groups['all'] %}{{hostvars[host]['ip_address']}}{% if not loop.last %},{% endif %}{% endfor %}"

- name: Create k8s env file
  ansible.builtin.template:
    src: k8s.env.j2
    dest: /etc/k8s.env
    mode: '0644'
    owner: root
    group: root

- include_tasks: cni.yml
  when: cni == "flannel"

- name: Add /usr/local/bin to PATH for all users
  ansible.builtin.copy:
    dest: /etc/profile.d/add-local-bin-to-path.sh
    content: |
      #!/bin/sh
      case ":$PATH:" in
        *:/usr/local/bin:*) ;;
        *) export PATH="/usr/local/bin:$PATH" ;;
      esac
    mode: '0755'

- include_tasks: cleanup.yml
