- name: Create folders
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  loop:
    - /etc/kubernetes/pki/etcd
    - /opt/cni/bin
    - /etc/cni/net.d

- include_tasks: certificate_authority.yml

- name: Install Base packages
  package:
    name: ['unzip','conntrack','curl','tar','git']

- include_tasks: cni.yml
  when: cni == "flannel"

- include_tasks: cleanup.yml
